// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-Pm-FI6tCuX9f2z-XlWnhB17ZjULItgI',
    appId: '1:92879990622:web:99ae104bd97642f272a9cf',
    messagingSenderId: '92879990622',
    projectId: 'mygp-d8c00',
    authDomain: 'mygp-d8c00.firebaseapp.com',
    storageBucket: 'mygp-d8c00.firebasestorage.app',
    measurementId: 'G-DTEJRMQCZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM-vCEtWlz1Zx3LRU86OxSRQgvqGt8Orc',
    appId: '1:92879990622:android:4f11f46a284b241d72a9cf',
    messagingSenderId: '92879990622',
    projectId: 'mygp-d8c00',
    storageBucket: 'mygp-d8c00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD96BdjjURFf40oDf0TG_-d7GpKty3a8l8',
    appId: '1:92879990622:ios:196985e5b91f72ef72a9cf',
    messagingSenderId: '92879990622',
    projectId: 'mygp-d8c00',
    storageBucket: 'mygp-d8c00.firebasestorage.app',
    iosBundleId: 'com.example.myGpFlutterUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD96BdjjURFf40oDf0TG_-d7GpKty3a8l8',
    appId: '1:92879990622:ios:671c844696e3020172a9cf',
    messagingSenderId: '92879990622',
    projectId: 'mygp-d8c00',
    storageBucket: 'mygp-d8c00.firebasestorage.app',
    iosBundleId: 'com.example.myGpFlutterUi.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-Pm-FI6tCuX9f2z-XlWnhB17ZjULItgI',
    appId: '1:92879990622:web:2e7d6994d1db07bf72a9cf',
    messagingSenderId: '92879990622',
    projectId: 'mygp-d8c00',
    authDomain: 'mygp-d8c00.firebaseapp.com',
    storageBucket: 'mygp-d8c00.firebasestorage.app',
    measurementId: 'G-BXHCPRT0D8',
  );
}
